python3 nfa-dfa.py ./regex-nfa_FIXED-output/1.txt ./nfa-dfa_outputs/1.txt
python3 nfa-dfa.py ./regex-nfa_FIXED-output/3.txt ./nfa-dfa_outputs/3.txt
python3 nfa-dfa.py ./regex-nfa_FIXED-output/4.txt ./nfa-dfa_outputs/4.txt
python3 nfa-dfa.py ./regex-nfa_FIXED-output/5.txt ./nfa-dfa_outputs/5.txt
python3 nfa-dfa.py ./regex-nfa_FIXED-output/6.txt ./nfa-dfa_outputs/6.txt
python3 nfa-dfa.py ./regex-nfa_FIXED-output/7.txt ./nfa-dfa_outputs/7.txt
python3 nfa-dfa.py ./regex-nfa_FIXED-output/8.txt ./nfa-dfa_outputs/8.txt
python3 nfa-dfa.py ./regex-nfa_FIXED-output/9.txt ./nfa-dfa_outputs/9.txt
python3 nfa-dfa.py ./regex-nfa_FIXED-output/10.txt ./nfa-dfa_outputs/10.txt
python3 nfa-dfa.py ./regex-nfa_FIXED-output/11.txt ./nfa-dfa_outputs/11.txt
python3 nfa-dfa.py ./regex-nfa_FIXED-output/12.txt ./nfa-dfa_outputs/12.txt
python3 nfa-dfa.py ./regex-nfa_FIXED-output/13.txt ./nfa-dfa_outputs/13.txt
