python3 regex-nfa_FIXED.py ./regex_INICIAL/1.txt ./regex-nfa_FIXED-output/1.txt
python3 regex-nfa_FIXED.py ./regex_INICIAL/2.txt ./regex-nfa_FIXED-output/2.txt
python3 regex-nfa_FIXED.py ./regex_INICIAL/3.txt ./regex-nfa_FIXED-output/3.txt
python3 regex-nfa_FIXED.py ./regex_INICIAL/4.txt ./regex-nfa_FIXED-output/4.txt
python3 regex-nfa_FIXED.py ./regex_INICIAL/5.txt ./regex-nfa_FIXED-output/5.txt
python3 regex-nfa_FIXED.py ./regex_INICIAL/6.txt ./regex-nfa_FIXED-output/6.txt
python3 regex-nfa_FIXED.py ./regex_INICIAL/7.txt ./regex-nfa_FIXED-output/7.txt
python3 regex-nfa_FIXED.py ./regex_INICIAL/8.txt ./regex-nfa_FIXED-output/8.txt
python3 regex-nfa_FIXED.py ./regex_INICIAL/9.txt ./regex-nfa_FIXED-output/9.txt
python3 regex-nfa_FIXED.py ./regex_INICIAL/10.txt ./regex-nfa_FIXED-output/10.txt
python3 regex-nfa_FIXED.py ./regex_INICIAL/11.txt ./regex-nfa_FIXED-output/11.txt
python3 regex-nfa_FIXED.py ./regex_INICIAL/12.txt ./regex-nfa_FIXED-output/12.txt
python3 regex-nfa_FIXED.py ./regex_INICIAL/13.txt ./regex-nfa_FIXED-output/13.txt
python3 regex-nfa_FIXED.py ./regex_INICIAL/14.txt ./regex-nfa_FIXED-output/14.txt
python3 regex-nfa_FIXED.py ./regex_INICIAL/15.txt ./regex-nfa_FIXED-output/15.txt
