python3 q1.py ./regular-expression/1.txt ./q1-output/1.txt
python3 q1.py ./regular-expression/2.txt ./q1-output/2.txt
python3 q1.py ./regular-expression/3.txt ./q1-output/3.txt
python3 q1.py ./regular-expression/4.txt ./q1-output/4.txt
python3 q1.py ./regular-expression/5.txt ./q1-output/5.txt
python3 q1.py ./regular-expression/6.txt ./q1-output/6.txt
python3 q1.py ./regular-expression/7.txt ./q1-output/7.txt
python3 q1.py ./regular-expression/8.txt ./q1-output/8.txt
python3 q1.py ./regular-expression/9.txt ./q1-output/9.txt
python3 q1.py ./regular-expression/10.txt ./q1-output/10.txt
python3 q1.py ./regular-expression/11.txt ./q1-output/11.txt
python3 q1.py ./regular-expression/12.txt ./q1-output/12.txt
python3 q1.py ./regular-expression/13.txt ./q1-output/13.txt
python3 q1.py ./regular-expression/14.txt ./q1-output/14.txt
python3 q1.py ./regular-expression/15.txt ./q1-output/15.txt
